import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta 
          name="fc:frame"
          content='{
    "version": "1",
    "name": "Mia Frame",
    "iconUrl": "https://themininextapp.vercel.app/icon.png",
    "homeUrl": "https://themininextapp.vercel.app",
    "imageUrl": "https://themininextapp.vercel.app/image.png",
    "buttonTitle": "Mia Next",
    "splashImageUrl": "https://themininextapp.vercel.app/splash.png",
    "splashBackgroundColor": "#401e12",
    "webhookUrl": "https://themininextapp.vercel.app/api/webhook",
    "subtitle" : "Dancing in the sun",
    "description" : "Here to play",
    "primaryCategory" : "Finance",
    "tagline": "hot",
    "ogTitle": "Gota"  
            }'
    
    />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
