import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta 
          name="fc:frame"
          content = '{ "version": "1" , "imageUrl": "https://themininextapp.vercel.app/public/window.svg", "button": { "title" : "Start", "action" : { "type": "launch_miniapp", "url" : "https://themininextapp.vercel.app/", "name" : "Next App", "splashImageUrl" : "https://themininextapp.vercel.app/public/next.svg", "splashBackgroundColor":"#401e12"}}}'
      />
      
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
