import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta 
          name="fc:frame"
          content = '{ "version": "1" , "imageUrl": "https://imgs.search.brave.com/t3nLe2_DyIWv9XQKTP-SE7-tA2OfZsxQWcli5sIo34U/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4t/ZnJvbnQuZnJlZXBp/ay5jb20vaG9tZS9h/bm9uLXJ2bXAvY3Jl/YXRpdmUtc3VpdGUv/c29jaWFsLW1lZGlh/L29uLWJyYW5kLndl/YnA", "button": { "title" : "Start", "action" : { "type": "launch_miniapp", "url" : "https://themininextapp.vercel.app/", "name" : "Next App", "splashImageUrl" : "https://themininextapp.vercel.app/public/next.svg", "splashBackgroundColor":"#401e12"}}}'
      />
      
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
